server:
  port: 8085
spring:
  application:
    name: springcloud-pay
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8088/eureka/
    register-with-eureka: true
    fetch-registry: true
